feat/legacy transactions
syscoin/pali-wallet pull request #302
Opened 2022-12-27 23:58 UTC by leozera14

feat: Add SendLegacyTransaction component to handle Legacy and EIP-1559 transactions from dApps.

2022-12-28 20:44 UTC, claudiovb requested changes
First review, still will add a commit with the fee and some packages fixes

2022-12-28 20:44 UTC, claudiovb commented on source/utils/ethUtil.ts
> +        method: 'Contract Interaction',
The method name for transactions where there is no data but a value included should be send

2022-12-28 20:44 UTC, claudiovb commented on source/utils/ethUtil.ts
> +    if (!data && value) {
Check if the value is 0 or '0x0'if this if would fail

2022-12-28 20:44 UTC, claudiovb commented on source/utils/ethUtil.ts
> +    if (!data && value) {
If this fails we should add some extra checking

2022-12-28 20:44 UTC, claudiovb commented on source/scripts/Provider/EthProvider.ts
> +    if ((tx.type && tx.type === '0x0') || (!tx.type && !tx.data)) {
Remove the tx type check here as we use this method for any sendTransaction case

2022-12-28 20:44 UTC, claudiovb commented on source/scripts/Provider/EthProvider.ts
> +    console.log('params', params);
Before we merge it remember removing the  console logs that are strict for testing

2023-01-02 13:32 UTC, claudiovb requested changes
Overall it is looking really good, all the changes are working properly testing on the e2e test Dapp. But there are some small fixes commented that are still needed also removing all the git warnings from the files before we can merge this PR. And there is a TODO as well that needs to be addressed regarding testing the other methods (Aprovve, SendTransaction - contract interactions) like on Pegasys, Luxy, Uniswap, and other methods from test Dapp as well so we can be assured no new bugs were brought by this changes.

2023-01-02 13:32 UTC, claudiovb commented on source/utils/fetchGasAndDecodeFunction.ts
> +  //TODO: test approve, sendTransaction for contract interactions and other components to check if its working aproppriately
Was this tested ?

2023-01-02 16:05 UTC, leozera14 commented on source/pages/Send/EditPriorityModal.tsx
> +        if (!isSendLegacyTransaction) {
Fixed

2023-01-02 16:05 UTC, leozera14 commented on source/utils/ethUtil.ts
> +    const transactionValueValidation = [value === 0, String(value) === '0x0'];
Fixed

2023-01-02 16:05 UTC, leozera14 commented on source/pages/Send/EditPriorityModal.tsx
> +              </div>
Fixed

2023-01-02 16:05 UTC, leozera14 commented on source/pages/Send/EditPriorityModal.tsx
> +        if (!isSendLegacyTransaction) {
Fixed

2023-01-02 16:06 UTC, leozera14 commented on package.json
> +}
Fixed

2023-01-03 15:57 UTC, claudiovb approved these changes

2023-01-03 16:01 UTC, merged