fix: solve not correct value displayed when max btn is used
syscoin/pali-wallet pull request #396
Opened 2023-06-06 01:48 UTC by lucasgabrielgsp

- [x] solve not correct value displayed when max btn is used

2023-06-11 19:38 UTC, claudiovb requested changes
Type syscoin assets and make tests through blockbook calls

2023-06-11 19:38 UTC, claudiovb commented on source/pages/Send/SendSys.tsx
> +        String(+selectedAsset.balance / 10 ** selectedAsset.decimals),
The fix seems to work well, but I noticed, for now, we have any type of syscoin assets. It's best to ensure we always will have decimals field for syscoin assets.
https://github.com/syscoin/pali-wallet/blob/ba7eb368b2a102793e1f86acc1768a3ec7f808be/source/state/vault/types.ts#L49

2023-06-21 02:23 UTC, leozera14 commented
Code seems legit and looks that fix the issue, only need to fix my Pali build to test it first before I can say it can be merged.

2023-06-21 15:11 UTC, leozera14 commented
I test it, found an error about decimals coming as undefined but already fixed it. Now is working and can merge it.

2023-06-28 00:51 UTC, claudiovb submitted a review, later dismissed

2023-06-28 01:26 UTC, claudiovb approved these changes

2023-06-28 01:26 UTC, merged