fix: remove utxo data from evm provider and vice versa
syscoin/pali-wallet pull request #404
Opened 2023-06-14 18:42 UTC by lucasgabrielgsp

- [x] remove utxo data from evm provider and vice versa

2023-06-26 21:44 UTC, claudiovb requested changes
We need to redo this PR, the proper form to avoid this is not dispatching the EVM only events while on UTXO change and vice-versa;
Additionally, we must set to null accountsArray and on EVM when changed to UTXO and also set to null xpub when switching from UTXO to EVM

2023-07-11 19:37 UTC, lucasgabrielgsp commented
> We need to redo this PR, the proper form to avoid this is not dispatching the EVM only events while on UTXO change and vice-versa; Additionally, we must set to null accountsArray and on EVM when changed to UTXO and also set to null xpub when switching from UTXO to EVM

Resolved

2023-07-21 14:00 UTC, leozera14 approved these changes

2023-07-21 14:04 UTC, lucasgabrielgsp reviewed
Ready for merge.

2023-07-21 15:46 UTC, claudiovb approved these changes

2023-07-21 16:59 UTC, merged