Refactor components
syscoin/pali-wallet pull request #66
Opened 2022-03-02 14:59 UTC by lucas-gauer

2022-03-07 18:19 UTC, lucas-gauer commented on source/components/Button/Button.tsx
> +  id = '',
```suggestion
  id = '0',
```

2022-03-08 17:58 UTC, amandagonsalves requested changes

2022-03-08 17:58 UTC, amandagonsalves commented on source/components/Layout/Layout.tsx
> +    <div className="relative w-full min-w-popup h-full min-h-popup text-brand-white bg-bkg-2">
layouts are breaking in fullscreen view

2022-03-08 17:58 UTC, amandagonsalves commented on source/components/Layout/TxLayout.tsx
> +  const accountCtlr = useController().wallet.account;
```suggestion
  const accountController = useController().wallet.account;
```

we don't need to abbreviate variable names, it is more difficult to read

2022-03-08 17:58 UTC, amandagonsalves commented on source/components/Layout/TxLayout.tsx
> +  const transaction = accountCtlr.getTemporaryTransaction(txType);
```suggestion
  const transaction = accountController.getTemporaryTransaction(txType);
```

2022-03-08 17:58 UTC, amandagonsalves commented on source/components/Layout/TxLayout.tsx
> +    accountCtlr.updateTemporaryTransaction({
```suggestion
    accountController.updateTemporaryTransaction({
```

2022-03-08 17:59 UTC, amandagonsalves commented on source/components/Layout/TxLayout.tsx
> +    accountCtlr.updateTemporaryTransaction({
there are also some conflicts to resolve before merge

2022-03-08 18:49 UTC, amandagonsalves approved these changes

2022-03-09 02:13 UTC, merged